# Generated by Django 6.0.1 on 2026-02-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_payment_options_alter_lesson_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Цена курса в рублях'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Цена урока в рублях'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stipe_price_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='id цены в stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='id сессии оплаты в stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_status',
            field=models.CharField(choices=[('paid', 'Оплачено'), ('unpaid', 'Неоплачено')], default='unpaid', max_length=20, verbose_name='Статус оплаты в stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка для оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='id продукта в stripe'),
        ),
    ]
