# Generated by Django 6.0.1 on 2026-02-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_price_lesson_price_payment_stipe_price_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_url',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка для оплаты'),
        ),
    ]
